# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juan López Salar
title: Analista de Datos | Bussiness Intelligence
email: ju.lopsalar@gmail.com
#website: https://julopsalar.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: 
github_username:  julopsalar
linkedin_username: juan-lopezs
# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: ju.lopsalar@gmail.com
#- title: another link
#  icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#  url: Link url (eg. https://google.com)


# About Section
about_title: Sobre mí
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Soy graduado en Ingeniería Informática por la Universidad de Murcia, trabajando actualmente como <i>Analista de Datos</i> en el sector del <i>Business Intelligence</i>. Me considero una persona con gran capacidad analítica, apasionado de los numeritos, datos y estadísticas. También siento gran inquietud por todo lo relacionado con la tecnología y la ciencia en general.

  Laboralmente, me he desarrollado en todas las fases del ciclo de datos, abarcando tanto la extracción, transformación y carga de datos como la visualización. Como prueba de mis intereses, en mi perfil de github destaco varios proyectos de programación que realicé para aprender a usar distintas herramientas.

# Además, también poseo una faceta creativa ciertamente importante, que en ocasiones me permite buscar soluciones diferentes a los problemas que se plantean: la música. Y es que soy músico de conservatorio, con el fagot como mi instrumento musical, con el que participo en bandas de música y orquestas. Y es que esto ha influido enormemente en mi persona, adquiriendo valores como la disciplina y el compañerismo.

  
content:
  - title: Experiencia laboral # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Analista de Datos
        link: https://metaenlace.com/
        # link_text: boringcompany.com
        sub_title: MetaEnlace Sistemas de Información
        caption: Oct 2025 - Act
        description: | # this will include new lines to allow paragraphs
          <u>Análisis y visualización de datos en Power BI</u>
          
          Creación de modelos analíticos y dashboards interactivos mediante Power BI para la visualización avanzada del dato y la toma de decisiones. Uso de Python y Amazon Web Services en la carga de los datos.

      - layout: left
        title: Desarrollador BI
        link: https://metaenlace.com/
        # link_text: boringcompany.com
        sub_title: MetaEnlace Sistemas de Información
        caption: Sept 2022 - Sept 2025
        description: | # this will include new lines to allow paragraphs
          <u>Diseño e implantación de procesos ETL</u>

          Desarrollo de procesos guiados por requisitos en un entorno Data Warehouse, utilizando la suite de <mark>Informatica Powercenter</mark>. Desarrollo, implementación y planificación de workflows mediante la tecnología de optimización Full PushDown.
          
          Acceso a diferentes sistemas gestores de bases de datos (Teradata, Oracle, Microsoft SQL Server).
            
  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Murcia
        link: https://www.um.es/web/informatica/
        caption: 2018 - 2022
        sub_title: Graduado en Ingeniería Informática
        description: | # this will include new lines to allow paragraphs
          El grado en Ingeniería Informática consta de 4 cursos, divididos en una fase general de 3 años en el que se desarrollan aspectos de hardware, software y científicos, y un último año específico. En mi caso cursé la mención en Ciencias de la Computación, con formación específica en <i>Modelos de Computación</i>, <i>Inteligencia Artificial</i> y <i>Machine Learning</i>.
          
        

  - title: Formación complementaria # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Data Analyst in Power BI
        link: https://www.datacamp.com/completed/statement-of-accomplishment/track/bc2e77d79b7ca57b1c74e448ad3001d843455d77
        link_text: Credencial
        caption: Dic 2025
        sub_title: DataCamp
        #quote: >
        #  La Universidad de Murcia es una institución referente a nivel nacional, tanto a nivel educativo como a nivel investigación.
        description: | # this will include new lines to allow paragraphs
          Esta certificación consiste en una serie de cursos de una duración total de 50 horas, con el fin de profundizar en el entorno de Power BI, siendo un gran punto de partida a la hora de preparar la certificación oficial de Microsoft (DA-300, en proceso...).
          

  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Clash Royale Data Scraping
        link: github.com/julopsalar/cr-data-mining
        # link_text: Project Website
        additional_links:
          - title:  julopsalar/cr-data-mining
            icon: fab fa-github
            url: github.com/julopsalar/cr-data-mining
          
        description: | # this will include new lines to allow paragraphs
          Uno de mis primeros proyectos de programación. Fue también una excusa para profundizar en el lenguaje <mark>Python</mark>, y familiarizarme con el uso y acceso a APIs (tanto un cliente oficial de la desarrolladora del videojuego como un wrapper desarrollado por parte de la comunidad). 
          El uso principal consiste en trackear las batallas de ciertas cuentas del videojuego móvil <i>Clash Royale</i>. Era una forma de personalizar el acceso a configuraciones y estrategias del juego, inspirado en webs como RoyaleAPI y StatsRoyale, muy famosas en su dia.
          
          En aquel momento, usaba <mark>dashboards</mark> sencillos desarrollados en <mark>Excel</mark> (Google Sheets), en el que compartir información con otros jugadores.  
        
      - layout: top-middle
        title: Futfem Dashboard
        link: github.com/julopsalar/futfem-analytics
        # link_text: Project Website
        additional_links:
          - title:  julopsalar/futfem-analytics
            icon: fab fa-github
            url: github.com/julopsalar/futfem-analytics
          
        description: | # this will include new lines to allow paragraphs
          El objetivo de este proyecto era el de aprender a utilizar herramientas de visualización (en este caso Power BI). Dado que hay multitud de proyectos de este tipo, decidí darle un enfoque algo distinto: acceder a los datos de competiciones de fútbol femenino. Por lo general, se encuentra menor cantidad de datos y visualización, por lo que me pareció interesante.
          En mi caso elegí realizar el data scraping manual, programado en Python, almacenado en una Base de Datos local.
          La visualización comprende desde visualización de tablas de clasificación, estadísticas de disparos, goles y otros eventos y comparación entre jugadoras en distintas métricas.



# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
